name: test-FT

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git fetch
      uses: actions/checkout@v1
      
    - name: Build
      run: g++ server.cpp -o serv.out
      
    - name: Test checks 
      run: test/test_checks.sh "serv.out"
      
    - name: Test checks 
      run: test/test_dummy.sh "serv.out"
