name: test-FT

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Hello
      run: echo "Hello world" -> a.txt
    - name: List files
      run: ls
    - name: try cat working
      run: cat a.txt
    - run: cat b.xtx
    - name: Done
      run: echo "Done"
